.nh
.TH rudo.conf 5 2021\-05\-29 0.8.6 "Rudo User manual"
.PP
# NAME
rudo.conf \- Configuration file for Rudo


.SH SYNOPSIS
.PP
/etc/rudo.conf


.SH DESCRIPTION
.PP
Rudo is a utility to gain privilege access on Unix system with Pam.

.PP
The configuration file consists of items in the format "Option: Value". A description of each item follows:

.PP
rudo
  impuser: Unix username of the user you want to impersonate

.PP
user:
  \- username: your Unix username
    group: the name of the group you must be a member to have privilege access
    password: true or false, if you want to give your password each session or not
    greeting: true or false if you want the hello message each time you run Rudo
  \- username: your Unix username
    group: the name of the group you must be a member to have privilege access
    password: true or false, if you want to give your password each session or not
    greeting: true or false if you want the hello message each time you run Rudo


.SH FILES
.PP
/etc/rudo.conf


.SH SEE ALSO
.PP
rudo(1)


.SH AUTHOR
.PP
Rémi Lauzier remilauzier@protonmail.com
\[la]mailto:remilauzier@protonmail.com\[ra]
