# Generated by rust2rpm 17
%bcond_without check
%global __cargo_skip_build 0

%global crate rudo

Name:           rust-%{crate}
Version:        0.7.1
Release:        1%{?dist}
Summary:        Utility to gain privilege access on Unix system with Pam

# Upstream license specification: GPL-2.0-or-later
License:        GPLv2+
URL:            https://crates.io/crates/rudo
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

Requires: pam
Requires: systemd-libs

BuildRequires:  rust-packaging

%global _description %{expand:
Utility to gain privilege access on Unix system with Pam.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%license LICENSE
%{_mandir}/man1/rudo.1*
%{_mandir}/man5/rudo.conf.5*
%attr(0644,root,root) %config(noreplace) %{_sysconfdir}/pam.d/rudo
%attr(0640,root,root) %config(noreplace) %{_sysconfdir}/rudo.conf
%attr(4755,root,root) %{_bindir}/rudo

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp conf/rudo ~/
cp conf/rudo.conf ~/
cp man/rudo.1 ~/
cp man/rudo.conf.5 ~/

%generate_buildrequires
%cargo_generate_buildrequires
echo "pam-devel"
echo "systemd-devel"

%build
%cargo_build

%install
%cargo_install
mkdir -p %{buildroot}/etc/
mkdir -p %{buildroot}/etc/pam.d/
mkdir -p %{buildroot}%{_mandir}/man1
mkdir -p %{buildroot}%{_mandir}/man5
install -m 0640 ~/rudo.conf %{buildroot}/etc/rudo.conf
install -m 0644 ~/rudo %{buildroot}/etc/pam.d/rudo
install -m 0644 ~/rudo.1 %{buildroot}%{_mandir}/man1/rudo.1
install -m 0644 ~/rudo.conf.5 %{buildroot}%{_mandir}/man5/rudo.conf.5

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 04 21:16:26 EDT 2021 Rémi Lauzier <remilauzier@protonmail.com> - 0.7.1-1
- Initial package
