# Generated by rust2rpm 17
%bcond_without check
%global __cargo_skip_build 0

%global crate rudo

Name:           rust-%{crate}
Version:        0.8.5
Release:        1%{?dist}
Summary:        Utility to gain privilege access on Unix system with Pam

# Upstream license specification: GPL-2.0-or-later
License:        GPLv2+
URL:            https://crates.io/crates/rudo
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Utility to gain privilege access on Unix system with Pam.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
Requires:       pam

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%license LICENSE
%{_mandir}/man1/rudo.1*
%{_mandir}/man5/rudo.conf.5*
%attr(0644,root,root) %config %{_sysconfdir}/pam.d/rudo
%attr(0640,root,root) %config(noreplace) %{_sysconfdir}/rudo.conf
%attr(4755,root,root) %{_bindir}/rudo

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install
mkdir -p %{buildroot}%{_sysconfdir}
mkdir -p %{buildroot}%{_sysconfdir}/pam.d/
mkdir -p %{buildroot}%{_mandir}/man1
mkdir -p %{buildroot}%{_mandir}/man5
install -pm 0640 conf/rudo.conf %{buildroot}%{_sysconfdir}/rudo.conf
install -pm 0644 conf/rudo %{buildroot}%{_sysconfdir}/pam.d/rudo
install -pm 0644 man/rudo.1 %{buildroot}%{_mandir}/man1/rudo.1
install -pm 0644 man/rudo.conf.5 %{buildroot}%{_mandir}/man5/rudo.conf.5

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 24 16:27:34 EDT 2021 Rémi Lauzier <remilauzier@protonmail.com> - 0.8.5-1
- Initial package
