# Generated by rust2rpm 17
%bcond_without check

%global crate rudo

Name:           rust-%{crate}
Version:        0.6.3
Release:        1%{?dist}
Summary:        Utility to gain privilege access on unix system with pam

# Upstream license specification: GPL-2.0-or-later
License:        GPLv2+
URL:            https://crates.io/crates/rudo
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

Requires: pam

BuildRequires:  rust-packaging

%global _description %{expand:
Utility to gain privilege access on unix system with pam.}

%description %{_description}

%if ! %{__cargo_skip_build}
%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%license LICENSE
%{_mandir}/man1/rudo.1*
%{_mandir}/man5/rudo.conf.5*
%attr(0644,root,root) %config(noreplace) %{_sysconfdir}/pam.d/rudo
%attr(0640,root,root) %config(noreplace) %{_sysconfdir}/rudo.conf
%attr(4755,root,root) %{_bindir}/rudo
%endif

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep
cp conf/rudo ~/
cp conf/rudo.conf ~/
cp man/rudo.1 ~/
cp man/rudo.conf.5 ~/

%generate_buildrequires
%cargo_generate_buildrequires
echo "pam-devel"
echo "systemd-devel"

%build
%cargo_build

%install
%cargo_install
mkdir -p %{buildroot}/etc/
mkdir -p %{buildroot}/etc/pam.d/
mkdir -p %{buildroot}%{_mandir}/man1
mkdir -p %{buildroot}%{_mandir}/man5
install -m 0640 ~/rudo.conf %{buildroot}/etc/rudo.conf
install -m 0644 ~/rudo %{buildroot}/etc/pam.d/rudo
install -m 0644 ~/rudo.1 %{buildroot}%{_mandir}/man1/rudo.1
install -m 0644 ~/rudo.conf.5 %{buildroot}%{_mandir}/man5/rudo.conf.5

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Fri Mar 26 21:42:40 EDT 2021 Rémi Lauzier <remilauzier@protonmail.com> - 0.6.3-1
- Initial package
